## Numpy Array and Basics 
Learn about Numpy 

In [ ]:
print("Hello World")

Hello World


In [ ]:
import numpy as np
import time

### Creating Array from List 

In [8]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ",arr_1d)

# arr_2d= np.array([1,2,3],[4,5,6]) // wrong because its take only array 
arr_2d= np.array([[1,2,3],[4,5,6]])
print("2D array: ",arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List V/S Numpy Array

In [ ]:
py_list = [1,2,3]
print("Python List Multiply:",py_list*2)

np_array=np.array([1,2,3])
print("Python Array Multiply:",np_array*2) # every element is multiplied by 2 

start=time.time()
py_list= [i*2 for i in range(1000000)]
print("\n List Operation time:", time.time() - start)

start = time.time()
np_array=np.arange(100000)
print("\n numpy Operation time:", time.time() - start)
# print(np_array)

Python List Multiply: [1, 2, 3, 1, 2, 3]
Python Array Multiply: [2 4 6]

 List Operation time: 0.1201632022857666

 numpy Operation time: 0.0004315376281738281
Sequence Array: [ 0  3  6  9 12 15]


### Creating Array From Scratch

In [32]:
zeros=np.zeros((3,4))
print("Zeros Array: \n",zeros)

one=np.ones((2,3))
print("Ones Array: \n",one)

full=np.full((3,3),4) #((tuples),parameter)
print("Full Array: \n",full)

random=np.random.random((3,3))
print("Random Array: \n",random) # always generate between 0 and 1 

sequence=np.arange(0,16,3) #(start,stop,step)
print("Sequence Array:",sequence)


Zeros Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array: 
 [[4 4 4]
 [4 4 4]
 [4 4 4]]
Random Array: 
 [[0.64935397 0.80986859 0.70344139]
 [0.94005444 0.77244169 0.63072136]
 [0.45893102 0.28838291 0.21523203]]
Sequence Array: [ 0  3  6  9 12 15]


### Vector Matrix And Tensor

In [44]:
vector = np.array({1,2,3})
print("Vector:",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix:\n",matrix)
# Matrix:
#  [[1 2 3]
#  [4 5 6]]

matrix2 = np.array([{1,2,3},
                   {4,5,6}])
print("Matrix:\n",matrix2)
#Matrix:
#  [{1, 2, 3} {4, 5, 6}]


tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor:\n",tensor)



Vector: {1, 2, 3}
Matrix:
 [[1 2 3]
 [4 5 6]]
Matrix:
 [{1, 2, 3} {4, 5, 6}]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr=np.array([[1,2,3],
              [4,5,6]])
print("Shape:",arr.shape)
print("Dimension:",arr.ndim)
print("Size:",arr.size)
print("Data Type:",arr.dtype) # float ,string-u21

Shape: (2, 3)
Dimension: 2
Size: 6
Data Type: int64


### Array Reshaping 


In [54]:
arr=np.arange(12)
print("Original Array:",arr)

reshape=arr.reshape((3,4))
print("Reshaped Array:\n",reshape)

flattened=reshape.flatten() # it return copy
print("Flatened Array:\n",flattened)

raveled=reshape.ravel() #its return original 
print("Raveled Array:\n",raveled)

transpose=reshape.T
print("Transpose Array:\n",transpose)


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatened Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Numpy Array Operations 

#### Slicing

In [57]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing:",arr[2:7])
print("With Step:",arr[1:8:2])
print("Negative:",arr[-3])


Basic slicing: [3 4 5 6 7]
With Step: [2 4 6 8]
Negative: 7


In [59]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print("Specific Element:",arr_2d[1,2])
print("Entire Row:",arr_2d[1:2])# row:column
print("Entire column:",arr_2d[:,2])

Specific Element: 6
Specific Element: [[4 5 6]]
Specific Element: [3 6 9]


### Sorting 

In [68]:
unsorted=np.array([1,2,3,4,2,3,56,76,43,34,0])
print("Unsorted Array:",unsorted)
print("Sorted Array:",np.sort(unsorted))

unsorted_2d=np.array([[1,2],[3,2],[3,1]])
# unsorted_2d=np.array([[3,1],[1,2],[2,3]])
print("Unsorted 2D Array:\n",unsorted_2d)
print("Sorted 2D Array by Column:\n",np.sort(unsorted_2d, axis=0))
print("Sorted 2D Array by Row:\n",np.sort(unsorted_2d, axis=1))

Unsorted Array: [ 1  2  3  4  2  3 56 76 43 34  0]
Sorted Array: [ 0  1  2  2  3  3  4 34 43 56 76]
Unsorted 2D Array:
 [[1 2]
 [3 2]
 [3 1]]
Sorted 2D Array by Column:
 [[1 1]
 [3 2]
 [3 2]]
Sorted 2D Array by Row:
 [[1 2]
 [2 3]
 [1 3]]


### Filter 

In [ ]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])

even_num=numbers[numbers%2==0] # its evaluate expression 

print("Even number:",even_num)

Even number: [ 2  4  6  8 10]
